version: '3'
services:
  rabbit1:
    image: si9ma/rabbitmq-server:3.7
    container_name: rabbit1
    build:
      context: ../rabbitmq
    hostname: rabbit1
    networks:
      - cluster-network
    environment:
      - RABBITMQ_DEFAULT_USER=si9ma
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  rabbit2:
    image: si9ma/rabbitmq-server:3.7
    container_name: rabbit2
    build:
      context: ../rabbitmq
    hostname: rabbit2
    networks:
      - cluster-network
    environment: 
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit1
      - RAM_NODE=true

  rabbit3:
    image: si9ma/rabbitmq-server:3.7
    container_name: rabbit3
    build:
      context: ../rabbitmq
    hostname: rabbit3
    networks:
      - cluster-network
    environment: 
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit1

  haproxy:
    image: haproxy:1.9
    container_name: haproxy
    volumes:
      - ./haproxy:/usr/local/etc/haproxy/:ro
    hostname: haproxy
    ports:
      - "5672:5672" # rabbitmq port
      - "15672:15672" # rabbitmq management port
      - "1936:1936" # haproxy stats port
    networks:
      - cluster-network

networks:
 cluster-network:
  driver: bridge