version: '3'
services:
  rabbit1:
    image: si9ma/rabbitmq-server:3.7
    build:
      context: .
    hostname: rabbit1
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypass
  rabbit2:
    image: si9ma/rabbitmq-server:3.7
    build:
      context: .
    hostname: rabbit2
    links:
      - rabbit1
    environment: 
    - CLUSTERED=true
    - CLUSTER_WITH=rabbit1
    - RAM_NODE=true
    ports:
        - "5673:5672"
        - "15673:15672"

  rabbit3:
    image: si9ma/rabbitmq-server:3.7
    build:
      context: .
    hostname: rabbit3
    links:
      - rabbit1
      - rabbit2
    environment: 
    - CLUSTERED=true
    - CLUSTER_WITH=rabbit1
    ports:
          - "5674:5672"
