version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    command: /bin/sh -c "echo `ip route show | awk '/default/ {print $$3}'` host >> /etc/hosts && nginx -g 'daemon off;'"
