version: '3.6'

services:
    redis:
        image: si9ma/redis:5
        build:
          context: .
        environment:
          - CLUSTER_MOD=true
        networks:
            - net
        deploy:
          replicas: 6
          update_config:
            parallelism: 2
            delay: 10s
          restart_policy:
            condition: on-failure

networks:
    net:
      driver: overlay
      attachable: true