version: '3.6'

services:
    redis:
        image: si9ma/redis:5.0.4-alpine
        hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
        build:
          context: .
        environment:
          - CLUSTERED=true
          - CLUSTER_NODES=6 # this value must equal to replicas
          - CLUSTER_SETUPER_SLOT=1 # the first slot task to setup cluster
          - SERVICE_NAME={{.Service.Name}}
          - SLOT={{.Task.Slot}}
        networks:
            - net
        deploy:
          replicas: 6
          update_config:
            parallelism: 2
            delay: 10s
          restart_policy:
            condition: on-failure

networks:
    net:
      driver: overlay
      attachable: true